### PR TITLE
Buy promos

### LINKED ISSUE #276: Add form to buy promotion

### PR DESCRIPTION
**Pull request by ajones55555**
closes https://github.com/Peer-Stevens/peer/issues/276

### CODE REVIEW

**Comment by elenirotsides** [comment]
When I click on `Promotions`, the `Notifications` and `Recommendations` buttons both become `Promotions`. Is this intended? @aej11a 

image

**Comment by elenirotsides** [comment]
Follow up comment: Do we want any of the fields to be required? I was able to see a success message even though I didn't fill out the payment info form. I know we're mocking the form right now, but we can still make the fields required, we just don't have to validate the data for correctness if that makes sense.

**Review by elenirotsides — COMMENTED** [review]
Everything looks good to me. I'm still wondering though about my question above, I think we should make the fields required to make it feel more real. We obviously won't be validating that card numbers and other information is valid, but I think we should at least make it required to fill in certain fields in order to see the success message.

**Comment by dcarpenter31** [comment]
hovering over a link looks a little janky atm, is fixing this a priority though?
promotions_hover
promotions_no_hover
(note how the underline just kinda scoots downward when you hover)

otherwise looks good to me

**Comment by dcarpenter31** [comment]
> Everything looks good to me. I'm still wondering though about my question above, I think we should make the fields required to make it feel more real. We obviously won't be validating that card numbers and other information is valid, but I think we should at least make it required to fill in certain fields in order to see the success message.

I think that this only becomes important once we expect to have real users personally, since the whole thing is mostly just for show

**Review by elenirotsides — APPROVED** [review]
I think this is a lot better now! Good stuff!

**Pull request merged**
